version: "3.9"

services:
  api:
    build: .
    image: geo-trials-api:latest
    container_name: geo-trails-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
