apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - middleware.yaml
  - ingress.yaml

images:
  - name: ghcr.io/ericafenyo/geo-trails-api
    newTag: ceb720d8a356a32b95c321e7926e80f0e725c5d6