name: CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/geo-trails-api:latest
            ghcr.io/${{ github.actor }}/geo-trails-api:${{ github.sha }}

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Update image tag in Kustomize
        run: |
          sed -i "s/newTag:.*/newTag: ${{ github.sha }}/" k8s/kustomization.yaml

      - name: Commit and push updated kustomization
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add k8s/kustomization.yaml
          git commit -m "Deploy ${{ github.sha }}"
          git push
